[package]
name = "datomish"
version = "0.4.0"
authors = ["Richard Newman <rnewman@twinql.com>", "Nicholas Alexander <nalexander@mozilla.com>"]

[dependencies]
rusqlite = "0.8.0"
clap = "2.19.3"

[dependencies.datomish-query-parser]
  path = "query-parser"
